name: Update Feature Branches after Main Merge

on:
  push:
    branches:
      - development
      - master
  pull_request:
    branches:
      - '**'
    types: [opened, synchronize, reopened]

jobs:
  update-branches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update feature branches
        run: |
          git fetch origin
          git checkout feature-branch
          git merge origin/main
          # Handle conflicts if any
          git push origin feature-branch
